export const dataLaporanAPI = [
        {
                id_laporan: 1,
                nomor_laporan: "290405-001",
                nama: "Joni",
                status: "pending",
                waktu: "13:00 WITA 29/04/2025",
                laporan: "Website Judol",
                laporanPreview: "https://static.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/p1/229/2024/07/08/judi-online-4-1292591587.jpg",
                petugas: "Dr. H. Ali Mazi, SH",
                alamat: "Kota Kendari",
                instansi: "KOMINFO",
                instansiPreview: "https://dfx.co.id/wp-content/uploads/2021/12/kominfo.png",
                batas_waktu: "1-5 Mei 2025",
                deskripsi: "Laporan ini ditujukan untuk menginformasikan adanya praktek pungutan liar yang sering terjadi di jalanan, wilayah kecamatan ABC.",
        },
        {
                id_laporan: 2,
                nomor_laporan: "290405-001",
                nama: "Joni",
                status: "proses",
                waktu: "13:00 WITA 29/04/2025",
                laporan: "Website Judol",
                laporanPreview: "https://static.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/p1/229/2024/07/08/judi-online-4-1292591587.jpg",
                petugas: "Dr. H. Ali Mazi, SH",
                alamat: "Kota Kendari",
                instansi: "KOMINFO",
                instansiPreview: "https://dfx.co.id/wp-content/uploads/2021/12/kominfo.png",
                batas_waktu: "1-5 Mei 2025",
                deskripsi: "Laporan ini ditujukan untuk menginformasikan adanya praktek pungutan liar yang sering terjadi di jalanan, wilayah kecamatan ABC.",
        },
        {
                id_laporan: 3,
                nomor_laporan: "290405-001",
                nama: "Joni",
                status: "selesai",
                waktu: "13:00 WITA 29/04/2025",
                laporan: "Website Judol",
                laporanPreview: "https://static.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/p1/229/2024/07/08/judi-online-4-1292591587.jpg",
                petugas: "Dr. H. Ali Mazi, SH",
                alamat: "Kota Kendari",
                instansi: "KOMINFO",
                instansiPreview: "https://dfx.co.id/wp-content/uploads/2021/12/kominfo.png",
                batas_waktu: "1-5 Mei 2025",
                deskripsi: "Laporan ini ditujukan untuk menginformasikan adanya praktek pungutan liar yang sering terjadi di jalanan, wilayah kecamatan ABC.",
        },
        {
                id_laporan: 4,
                nomor_laporan: "290405-001",
                nama: "Joni",
                status: "tolak",
                waktu: "13:00 WITA 29/04/2025",
                laporan: "Website Judol",
                laporanPreview: "https://static.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/p1/229/2024/07/08/judi-online-4-1292591587.jpg",
                petugas: "Dr. H. Ali Mazi, SH",
                alamat: "Kota Kendari",
                instansi: "KOMINFO",
                instansiPreview: "https://dfx.co.id/wp-content/uploads/2021/12/kominfo.png",
                batas_waktu: "1-5 Mei 2025",
                deskripsi: "Laporan ini ditujukan untuk menginformasikan adanya praktek pungutan liar yang sering terjadi di jalanan, wilayah kecamatan ABC.",
        },
        
] 